name: Manual Build - Base64 Output

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build extension (Chrome)
        run: npm run build:prod:zip:chrome

      - name: List ZIPs
        run: |
          echo "🔍 Looking for ZIP files..."
          find . -type f -name "*.zip"

      - name: Encode the ZIP file to base64
        run: |
          echo "📦 Encoding the ZIP file..."
          ZIP_PATH=$(find . -type f -name "*.zip" | head -n 1)
          echo "Found ZIP at: $ZIP_PATH"
          echo "-----BEGIN BASE64-----"
